# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{compass-web-app-theme}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Drew Chandler"]
  s.date = %q{2010-10-21}
  s.description = %q{A port of Andrea Franz's web-app-theme in compass with semantic markup}
  s.email = %q{andrewschandler@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "compass-web-app-theme.gemspec",
     "lib/compass-web-app-theme.rb",
     "stylesheets/_web-app-theme.scss",
     "stylesheets/web-app-theme/themes/_drastic-dark.scss"
  ]
  s.homepage = %q{http://github.com/drewchandler/compass-web-app-theme}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{web-app-theme in compass}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

